
# This is a basic workflow to help you get started with Actions

name: Build

# Controls when the action will run. 
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Clone Github Repo 
        uses: actions/checkout@v2

      # Download Java
      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: '12.x'

      # Download Flutter
      - name: Setup Flutter
        uses: subosito/flutter-action@v1
        with:
          flutter-version: '2.10.2'

      # Update Flutter if needed
      - name: Upgrade Flutter
        run: flutter doctor

      # Run Flutter doctor
      - name: Flutter Doctor
        run: flutter doctor

      # Download packages  
      - name: Download packages
        run: flutter pub get

      # Build the APK file
      - name: Build APK
        run: flutter build apk

      # Upload the APK file
      - name: Upload APK
        uses: actions/upload-artifact@master
        with:
          name: Android-Application
          path: build/app/outputs/apk/release/app-release.apk
